docs: Java, Spring, CI/CD 추가
ksundong/backend-interview-question pull request #10
Opened 2021-01-26 07:52 UTC by kses1010

2021-01-26 12:56 UTC, ksundong requested changes
써니!! 기여 감사합니다!!
전반적으로 좀 더 좋은 내용을 담고자 여러 제안을 했습니다. 확인하시고 의견달아주세요~

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>인터페이스는 구현 객체가 같은 동작을 한다는 것을 보장하기 위해 사용합니다. 다중 상속이 가능합니다.</p>
객체의 추상화가 추상클래스가 맞을까요? 그리고 일반 메서드는 재정의를 할 수도 있다는 점이 잘 드러나지 않는 것 같습니다.
추상클래스와 인터페이스의 차이점인 단일 상속 vs 다중상속이 드러나지 않는 것 같습니다.
또한 추상클래스와 인터페이스의 또 다른 차이로는 추상클래스를 상속하는 집합간에는 연관관계가 있지만, 인터페이스를 구현하는 집합간에는 관계가 없을 수 있다는 점도 있을 것 같네요!

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>인터페이스는 구현 객체가 같은 동작을 한다는 것을 보장하기 위해 사용합니다. 다중 상속이 가능합니다.</p>
일반 메서드의 재정의에는 또한 LSP도 엮어서 질문이 가능할 것 같네요!

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>객체는 식별 가능한 개체 또는 사물입니다. 객체는 구별 가능한 식별자, 특징적인 행동, 변경 가능한 상태를 가집니다.</p>
인스턴스들을 통칭하는 용도로 객체를 쓰기도 합니다.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <summary>정적(Static)이란 무엇인가요?</summary>
```suggestion
  <summary>정적(static)이란 무엇인가요?</summary>
```

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>Static은 클래스 멤버라고 하며, 클래스 로더가 클래스를 로딩해서 메소드 메모리 영역에 적재할 때 클래스별로 관리됩니다.</p>
```suggestion
  <p>static은 클래스 멤버라고 하며, 클래스 로더가 클래스를 로딩해서 메소드 메모리 영역에 적재할 때 클래스별로 관리됩니다.</p>
```

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>Static 키워드를 통해 생성된 정적멤버들은 Static 영역에 할당되며 Static 영역에 할당된 메모리는 모든 객체가 공유하며 하나의 멤버를 어디서든지 참조할 수 있는 장점이 있습니다.</p>
```suggestion
  <p>static 키워드를 통해 생성된 정적멤버들은 Static 영역에 할당되며 Static 영역에 할당된 메모리는 모든 객체가 공유하며 하나의 멤버를 어디서든지 참조할 수 있는 장점이 있습니다.</p>
```

Static 영역이 무엇인가요? JVM 메모리 구조에는 static area라는 곳은 없습니다.
PermGen 혹은 Metaspace에 저장이 되는 것으로 알고있습니다.

https://www.linkedin.com/pulse/static-variables-methods-java-where-jvm-stores-them-kotlin-malisciuc/

어디서든지 참조할 수 있다는 점은 장점이 될 수도 단점이 될 수도 있다고 봅니다. 가령 final로 선언하지 않은 static variable은 오작동의 주범이 될 가능성이 농후합니다.

가급적이면 설계 시 static을 지양하는 것이 좋다는 자료들도 많이 올라오기 때문에 특징정도로 설명해주는 것이 좋을 듯 합니다.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>OCP(개방-폐쇄 원칙)은 확장에는 열려 있으나 변경에는 닫혀 있어야 하며, 다형성을 활용해야 합니다.</p>
https://www.linkedin.com/pulse/solid-design-principles-open-closed-principle-ocp-amritpal-singh/

다형성을 활용해야 한다라는 내용이 납득은 가는데, 좀 더 조사를 해봤더니 밥아저씨가 다형성과 연관지어서 써야한다고 하셨군요.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>LSP(리스코프 치환 원칙)은 프로그램의 객체는 프로그램의 정확성을 깨뜨리지 않으면서 하위 타입의 인스턴스로 바꿀 수 있어야하는 원칙으로 이 예시는 `List<Integer> intList = new ArrayList<>();` 와 같습니다.</p>
이거 마크다운 코드 먹나요? 안먹을텐데...
예시가 뭔가 좀 애매한 느낌입니다.

그리고 하위 타입의 인스턴스가 상위 타입을 대체할 수 있어야한다는 의미로 생각하고 있는데, 반대로 설명하는 느낌이네요.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>ISP(인터페이스 분리 원칙)은 클라이언트는 자신이 사용하지 않는 메서드에 의존 관계를 맺으면 안되는 원칙입니다. 특정 클라이언트를 위한 인터페이스 여러 개가 범용 인터페이스 하나보다 더 낫습니다.</p>
비대한 인터페이스를 더 작고 구체적인 인터페이스로 분리한다는 내용도 추가하면 좋지 않을까 싶습니다.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>DIP(의존관계 역전 원칙)은 구현 클래스에 의존하지 말고, 인터페이스에 의존해야 하는 원칙입니다. 자신보다 변하기 쉬운 구체에 의존하면 안됩니다.</p>
클래스, 인터페이스라는 용어를 사용하기 보다는
추상적인 것은 자신보다 구체적인 것에 의존하지 않고, 변화하기 쉬운 것에 의존해서는 안된다. 라고 설명하는 것이 어떨까 싶어요?

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>하나의 객체를 여러 스레드에서 동시에 사용할 경우에 동기화를 사용합니다. Java에서는 synchronized 키워드를 사용하여 스레드를 통제합니다. Collections에서는 JDK1.7부터 concurrent package를 통해 ConcurrentHashMap이라는 구현체를 사용니다.</p>
이 부분은 좀 더 내용 보완해주시는게 좋을 것 같아요.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>POJO는 프레임워크 인터페이스, 클래스를 구현하거나 확장하지 않은 단순한 클래스로 Java에서 제공하는 API 외에 종속되지 않습니다. 특정 환경에 종속되지 않아 코드가 간결하고 테스트 자동화에 유리합니다.</p>
Spring Framework에서 POJO는 무엇이 될 수 있을까요?
요 질문이 중요합니다 ㅎㅎ

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>가끔 면접에서 싱글톤 클래스를 만들라고 요구할 때도 있습니다. 그럴 때는 간단한 싱글톤 클래스를 준비하는게 좋습니다.</p>
싱글턴 패턴의 구현 방법은 굉장히 많습니다.
간단한 싱글턴은 큰 의미가 없습니다. 동시성환경에서 간단한 싱글턴이 문제가 되고, 이를 아는가, 이에 대한 해결방법에 대해서 찾아본 적이 있는가가 이 질문의 의도입니다.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>코드 버전 관리를 하는 VCS 시스템에 push가 되면 테스트와 빌드가 수행되어 안정적인 배포파일을 만드는 과정을 CI(지속적 통합)이라고 하며, 이 빌드 결과를 자동으로 운영 서버에 배포까지 되는 과정을 CD(지속적 배포)라고 합니다.</p>
CD는 최근 Delivery와 Deployment를 모두 포함하고 있습니다.

2021-01-26 12:56 UTC, ksundong commented on README.md
>  </details>
좋은 질문과 답변 감사합니다.

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  </ul>
모 강사님의 강의가 생각나네요. 👍

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>request는 웹 요청이 들어오고 나갈때까지 유지하는 스코프, session은 웹 세션이 생성, 종료할때까지, application은 웹 서블릿 컨텍스와 같은 범위로 유지하는 스코프입니다.</p>
```suggestion
  <p>request는 웹 요청이 들어오고 나갈때까지 유지하는 스코프, session은 웹 세션이 생성, 종료할때까지, application은 웹 서블릿 컨텍스트와 같은 범위로 유지하는 스코프입니다.</p>
```

2021-01-26 12:56 UTC, ksundong commented on README.md
> +  <p>컨테이너 안에 들어있는 객체로 필요할 때 컨테이너에서 가져와서 사용합니다. `@Bean` 을 사용하거나 xml설정을 통해 일반 객체를 Bean으로 등록할 수 있습니다.</p>
```suggestion
  <p>IoC 컨테이너 안에 들어있는 객체로 필요할 때 IoC 컨테이너에서 가져와서 사용합니다. `@Bean` 을 사용하거나 xml설정을 통해 일반 객체를 Bean으로 등록할 수 있습니다.</p>
```

2021-01-27 13:02 UTC, kses1010 commented on README.md
> +  <p>JVM의 구조는 Class Loader, Exection engine, GC, Runtime Data Area로 이루어져 있습니다.</p>
네 수정하겠습니다

2021-01-27 13:03 UTC, kses1010 commented on README.md
> +  <p>Java Collection은 널리 알려져 있는 자료구조를 바탕으로 객체, 데이터들을 효율적으로 관리 할 수 있는 자료구조들이 있는 라이브러리를 컬렉션 프레임워크라고 합니다. 배열과 다르게 객체의 수를 상황에 따라 동적으로 정할 수 있습니다.</p>
List + Set // Map으로 구분해보겠습니다

2021-01-27 13:06 UTC, kses1010 commented on README.md
> +  <p>애너테이션은 인터페이스를 기반으로 한 문법으로 주석처럼 코드에 달아 클래스에 특별한 의미를 부여하거나 기능을 주입할 수 있습니다. built-in annotation은 상속받아서 메소드를 오버라이드 할 때 나타나는 @Override 애너테이션이 그 대표적인 예입니다.</p>
메타 애너테이션도 추가해볼게요. 예시는 한가지 정도?로 추가해보겠습니다

2021-01-27 13:07 UTC, kses1010 commented on README.md
> +  <p>인터페이스는 구현 객체가 같은 동작을 한다는 것을 보장하기 위해 사용합니다. 다중 상속이 가능합니다.</p>
가장 큰 차이점인 단일 상속 vs 다중 상속을 앞에 표시하겠습니당

2021-01-27 13:07 UTC, kses1010 commented on README.md
> +  <p>객체는 식별 가능한 개체 또는 사물입니다. 객체는 구별 가능한 식별자, 특징적인 행동, 변경 가능한 상태를 가집니다.</p>
그것도 추가해보겠습니다. 오브젝트에서 참고해봤는데 인스턴스들을 통칭하는 용도라고 추가해보겠습니다.

2021-01-27 13:09 UTC, kses1010 commented on README.md
> +  <p>Static 키워드를 통해 생성된 정적멤버들은 Static 영역에 할당되며 Static 영역에 할당된 메모리는 모든 객체가 공유하며 하나의 멤버를 어디서든지 참조할 수 있는 장점이 있습니다.</p>
설계 시 지양하는 것이 좋다는 것을 부각 시켜보겠습니다.

2021-01-27 13:20 UTC, kses1010 commented on README.md
> +  <p>LSP(리스코프 치환 원칙)은 프로그램의 객체는 프로그램의 정확성을 깨뜨리지 않으면서 하위 타입의 인스턴스로 바꿀 수 있어야하는 원칙으로 이 예시는 `List<Integer> intList = new ArrayList<>();` 와 같습니다.</p>
김영한님 강의에서 LSP를 위와 같이 강의하셨습니다. 마크다운 코드 안먹으면 삭제하도록 하겠습니다.
![image](https://user-images.githubusercontent.com/49144662/105996503-c1362980-60ed-11eb-9cf9-beed171e15b4.png)

2021-01-27 13:22 UTC, kses1010 commented on README.md
> +  <p>ISP(인터페이스 분리 원칙)은 클라이언트는 자신이 사용하지 않는 메서드에 의존 관계를 맺으면 안되는 원칙입니다. 특정 클라이언트를 위한 인터페이스 여러 개가 범용 인터페이스 하나보다 더 낫습니다.</p>
> 특정 클라이언트를 위한 인터페이스 여러 개가 범용 인터페이스 하나보다 더 낫습니다.

이 내용이 말씀하시는 것과 비슷한데 어느 것이 나으신가요? 저는 범용 인터페이스라는 표현이 좋다고 생각하여 표현했는데 의견이 궁금합니다.

2021-01-27 13:23 UTC, kses1010 commented on README.md
> +  <p>DIP(의존관계 역전 원칙)은 구현 클래스에 의존하지 말고, 인터페이스에 의존해야 하는 원칙입니다. 자신보다 변하기 쉬운 구체에 의존하면 안됩니다.</p>
같이 추가하는게 좋겠네요. 면접에서 설명할 때 추상적, 구체적이라고 말하니 예시? 구체적? 으로 다시한번 물어보시더라구요. 그래서 구현 클래스, 인터페이스라고 표현했습니다.

2021-01-27 13:24 UTC, kses1010 commented on README.md
> +  <p>하나의 객체를 여러 스레드에서 동시에 사용할 경우에 동기화를 사용합니다. Java에서는 synchronized 키워드를 사용하여 스레드를 통제합니다. Collections에서는 JDK1.7부터 concurrent package를 통해 ConcurrentHashMap이라는 구현체를 사용니다.</p>
어느 부분을 보완하시면 좋은지 구체적으로 알려주시면 감사합니다.

2021-01-27 13:26 UTC, kses1010 commented on README.md
> +  <p>POJO는 프레임워크 인터페이스, 클래스를 구현하거나 확장하지 않은 단순한 클래스로 Java에서 제공하는 API 외에 종속되지 않습니다. 특정 환경에 종속되지 않아 코드가 간결하고 테스트 자동화에 유리합니다.</p>
무엇이 되는지라면 DTO입니다. 라고해도 될까요?
https://www.baeldung.com/java-pojo-class

2021-01-27 13:28 UTC, kses1010 commented on README.md
> +  <p>가끔 면접에서 싱글톤 클래스를 만들라고 요구할 때도 있습니다. 그럴 때는 간단한 싱글톤 클래스를 준비하는게 좋습니다.</p>
흐음 이거 토비 스프링에서 본 건데 추가할까 말까 고민했는데 질문의 의도를 알겠으니 조금 더 추가해보겠습니다.

2021-01-27 13:29 UTC, kses1010 commented on README.md
> +  <p>코드 버전 관리를 하는 VCS 시스템에 push가 되면 테스트와 빌드가 수행되어 안정적인 배포파일을 만드는 과정을 CI(지속적 통합)이라고 하며, 이 빌드 결과를 자동으로 운영 서버에 배포까지 되는 과정을 CD(지속적 배포)라고 합니다.</p>
그렇네요 either라고 표현하네요.

2021-01-27 13:30 UTC, kses1010 commented on README.md
> +  <p>컨테이너 안에 들어있는 객체로 필요할 때 컨테이너에서 가져와서 사용합니다. `@Bean` 을 사용하거나 xml설정을 통해 일반 객체를 Bean으로 등록할 수 있습니다.</p>
여기도 코드표시 지워야겠어요

2021-01-27 13:52 UTC, ksundong commented on README.md
> +  <p>LSP(리스코프 치환 원칙)은 프로그램의 객체는 프로그램의 정확성을 깨뜨리지 않으면서 하위 타입의 인스턴스로 바꿀 수 있어야하는 원칙으로 이 예시는 `List<Integer> intList = new ArrayList<>();` 와 같습니다.</p>
네, 말하고자 하는 바는 같은데, LSP의 정의는 하위타입의 인스턴스가 상위 타입처럼 행동해야 한다는게 맞습니다.
애초에 나온 계기가, '상위 타입을 만약에 상속해서 재정의 하면 프로그램이 깨지지 않을까?'가 먼저여서요.

말하고자 하는 바는 같지만, 좀 더 이론적 배경을 바탕으로 설명하는게 맞지 않나 싶어요.

2021-01-27 13:53 UTC, ksundong commented on README.md
> +  <p>ISP(인터페이스 분리 원칙)은 클라이언트는 자신이 사용하지 않는 메서드에 의존 관계를 맺으면 안되는 원칙입니다. 특정 클라이언트를 위한 인터페이스 여러 개가 범용 인터페이스 하나보다 더 낫습니다.</p>
둘 다 넣어야죠 ㅎㅎ

2021-01-27 13:55 UTC, ksundong commented on README.md
> +  <p>DIP(의존관계 역전 원칙)은 구현 클래스에 의존하지 말고, 인터페이스에 의존해야 하는 원칙입니다. 자신보다 변하기 쉬운 구체에 의존하면 안됩니다.</p>
그런 질문이 추가적으로 있었군요.
하지만, 원론적으로 설명하고 써니가 겪으셨던 것처럼 구체적인 것은 나중에 설명하는 것이 좋은 것 같아요.
왜냐하면, 질문의 의도가 이론을 아는가? → 그럼 실제로 적용할 줄 아는가? 였던 것 같거든요.

2021-01-27 13:56 UTC, ksundong commented on README.md
> +  <p>하나의 객체를 여러 스레드에서 동시에 사용할 경우에 동기화를 사용합니다. Java에서는 synchronized 키워드를 사용하여 스레드를 통제합니다. Collections에서는 JDK1.7부터 concurrent package를 통해 ConcurrentHashMap이라는 구현체를 사용니다.</p>
음... 어디부터 설명해드려야 할지 모르겠어요.
백기선님 라이브 스터디 관련 자료들 이번에 동기화와 관련된 내용이 나왔었는데, 그 부분을 읽어보시고 보충하시면 도움이 되지 않을까 싶네요?

2021-01-27 13:57 UTC, ksundong commented on README.md
> +  <p>POJO는 프레임워크 인터페이스, 클래스를 구현하거나 확장하지 않은 단순한 클래스로 Java에서 제공하는 API 외에 종속되지 않습니다. 특정 환경에 종속되지 않아 코드가 간결하고 테스트 자동화에 유리합니다.</p>
@kses1010
정말요? 써니가 스프링 관련 코드를 작성할 때, 정말 POJO가 그것밖에 없나요?

2021-01-27 13:58 UTC, ksundong commented
@kses1010 
리뷰 내용에 코멘트 남겨두신 부분 답변합니다.
확인 부탁드려요~

2021-01-27 14:05 UTC, kses1010 commented on README.md
> +  <p>LSP(리스코프 치환 원칙)은 프로그램의 객체는 프로그램의 정확성을 깨뜨리지 않으면서 하위 타입의 인스턴스로 바꿀 수 있어야하는 원칙으로 이 예시는 `List<Integer> intList = new ArrayList<>();` 와 같습니다.</p>
좀 길어질거 같고 거기까지 이야기는 왠만큼 하지않더라구요

2021-01-27 14:05 UTC, kses1010 commented on README.md
> +  <p>ISP(인터페이스 분리 원칙)은 클라이언트는 자신이 사용하지 않는 메서드에 의존 관계를 맺으면 안되는 원칙입니다. 특정 클라이언트를 위한 인터페이스 여러 개가 범용 인터페이스 하나보다 더 낫습니다.</p>
그럼 둘 다 넣을게요

2021-01-27 14:05 UTC, kses1010 commented on README.md
> +  <p>DIP(의존관계 역전 원칙)은 구현 클래스에 의존하지 말고, 인터페이스에 의존해야 하는 원칙입니다. 자신보다 변하기 쉬운 구체에 의존하면 안됩니다.</p>
원론 + 구체적으로 설명을 풀어보겠습니다.

2021-01-27 14:06 UTC, kses1010 commented on README.md
> +  <p>하나의 객체를 여러 스레드에서 동시에 사용할 경우에 동기화를 사용합니다. Java에서는 synchronized 키워드를 사용하여 스레드를 통제합니다. Collections에서는 JDK1.7부터 concurrent package를 통해 ConcurrentHashMap이라는 구현체를 사용니다.</p>
그 부분 링크 부탁드립니다. 왜냐하면 동시성 이슈라는게 한문단으로 끝낼 문제는 아니라고 생각하거든요.
내용이 엄청 길어질 겁니다. 그래서 어디까지 이야기를 해야하는가 어디서 끊어야 하는가의 기준이 필요합니다.

2021-01-27 14:08 UTC, kses1010 commented on README.md
> +  <p>POJO는 프레임워크 인터페이스, 클래스를 구현하거나 확장하지 않은 단순한 클래스로 Java에서 제공하는 API 외에 종속되지 않습니다. 특정 환경에 종속되지 않아 코드가 간결하고 테스트 자동화에 유리합니다.</p>
그럼 예시는 지우는 걸로.. 예시를 제가 DTO외에는 어디 썼는지 모르겠네요.

2021-01-28 11:36 UTC, ksundong commented on README.md
> +  <p>LSP(리스코프 치환 원칙)은 프로그램의 객체는 프로그램의 정확성을 깨뜨리지 않으면서 하위 타입의 인스턴스로 바꿀 수 있어야하는 원칙으로 이 예시는 `List<Integer> intList = new ArrayList<>();` 와 같습니다.</p>
음.. 어떤부분이 길다고 느끼셨는지 궁금하네요.
그리고, 거기까지 이야기 하지 않는다는 얘기도 어디서 나왔는지 궁금합니다.

오브젝트 책의 내용을 빌려 설명하자면
"서브타입은 그것의 기반 타입에 대해 대체 가능해야 한다"
클라이언트가 "차이점을 인식하지 못한 채 파생 클래스의 인터페이스를 통해 서브클래스를 사용할 수 있어야한다"
입니다.

당연히 영한님이 하신 말씀도 맞는데, 제가 생각하기에는 서브 타입이 대체 되기 위한 조건을 설명하는것이 더 중요할 것 같다고 생각이되네요.

2021-01-28 11:43 UTC, ksundong commented on README.md
> +  <p>하나의 객체를 여러 스레드에서 동시에 사용할 경우에 동기화를 사용합니다. Java에서는 synchronized 키워드를 사용하여 스레드를 통제합니다. Collections에서는 JDK1.7부터 concurrent package를 통해 ConcurrentHashMap이라는 구현체를 사용니다.</p>
- volatile
- immutable object

- synchronized block, method
- ReentrantLock(필수 x)
- concurrent utils
- atomic

이 내용이 전부 포함되어있어야 한다고 생각합니다.

아래 링크 한 번 참고해보세요.
https://velog.io/@nunddu/Java-%EB%8F%99%EA%B8%B0%EB%A5%BC-%EB%B3%B4%EC%9E%A5%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95

공유자원 접근이라는 내용으로 충분하다고 생각했는데, 어떤 부분을 더 보완해주실 수 있는지도 알려주시면 감사하겠습니다.
동시성 이슈에 대해서 써니에게 한 번 들어보고 싶네요.

2021-01-28 11:55 UTC, ksundong commented on README.md
> +  <p>POJO는 프레임워크 인터페이스, 클래스를 구현하거나 확장하지 않은 단순한 클래스로 Java에서 제공하는 API 외에 종속되지 않습니다. 특정 환경에 종속되지 않아 코드가 간결하고 테스트 자동화에 유리합니다.</p>
결국 객체지향적으로 돌아가기 위해서 POJO라는 용어가 나왔으니
우리가 작성하는 프로그램에서 객체가 될 수 있는 것은 무엇인가? 라는 생각을 해보면 좋을 것 같아요.

사실 저도 정답은 정확히 무엇이라고 딱 정하긴 어렵다고 생각해요. POJO의 정의상 순수한 자바 객체 + 애노테이션 정도가 POJO라고 불릴 수 있는데, 제가 답변했던 기억으로는 도메인과 비즈니스 로직을 수행하는 대상이라고 답했던 것 같아요.

2021-02-07 13:39 UTC, ksundong approved these changes
일단 머지하겠습니다 ㅎㅎ
고생하셨습니다!

2021-02-07 13:39 UTC, merged

2021-02-07 15:41 UTC, ksundong reviewed
@kses1010 
리뷰내용 남깁니다!
확인하시고 다음 PR에 반영해주실 수 있는 내용은 반영 부탁드려요!

2021-02-07 15:41 UTC, ksundong commented on README.md
> +      <li>JIT 컴파일러: 인터피르터 효율을 높이기 위한 컴파일러로 인터프리터가 반복되는 코드를 발견하면 JIT 컴파일러가 반복되는 코드를 네이티브 코드로 바꿔줍니다. 그 다음부터 인터프리터는 네이티브 코드로 컴파일된 코드를 바로 사용합니다.</li>
@kses1010 
인터피르터 → 인터프리터로 수정부탁드려요!
JIT 컴파일러가 동작하기 위해서는 최소 한 번은 실행되어야 한다는 부분도 추가되면 좋을 것 같네요.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +      <li>GC(Garbage Collector): 가비지 컬렉터로 힙 영역에서 사용되지 않는 객체들을 제거하는 작업을 의미합니다.</li>
작업은 Garbage Collection, Garbage Collector는 실행하는 모듈로 알아두는 것이 더 좋겠네요!

2021-02-07 15:41 UTC, ksundong commented on README.md
> +    <li>JNI(Java Native Interface): 자바 애플리케이션에서 C, C++, 어셈블리어로 작성된 함수를 사용할 수 있는 방법을 제공해줍니다. Native 키워드를 사용하여 메서드를 호출합니다. 대표적인 메서드는 Thread의 currentThread()입니다.</li>
키워드는 `native`입니다. 대문자랑 소문자를 구분해서 사용하는 것이 좋아보여요.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +    <li>Class Loader를 통해 class 파일들을 JVM으로 로딩합니다.</li>
이 때 클래스는 동적로딩 된다는 것도 첨언하면 좋을 것 같아요.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>제네릭은 자바의 타입 안정성을 맡고 있습니다. 컴파일 과정에서 타입체크를 해주는 기능으로 객체의 타입을 컴파일 시에 체크하기 때문에 객체의 타입 안정성을 높이고 형변환의 번거로움을 줄여줍니다.</p>
이 대답은 진짜 좋은 것 같아요 👍

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>애노테이션은 인터페이스를 기반으로 한 문법으로 주석처럼 코드에 달아 클래스에 특별한 의미를 부여하거나 기능을 주입할 수 있습니다. built-in annotation은 상속받아서 메소드를 오버라이드 할 때 나타나는 @Override 애노테이션이 그 대표적인 예입니다.</p>
<code> 였나 <pre>였나 있을거에요. 코드는 그걸로 묶어주시면 될 것 같아요.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +    <li>@Retention: 애노테이션 유지 범위를 지정합니다. (소스, 클래스, 런타임)</li>
요거는 SOURCE, CLASS, RUNTIME이라는 걸로 적어주는게 더 좋아보여요.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>추상클래스는 객체의 추상적인 상위 개념으로 공통된 개념을 표현할 때 사용합니다. 단일 상속만 가능합니다. 추상클래스를 상속하는 집합간에는 연관관계가 있습니다.</p>
추상클래스는 클래스의 추상적인 범위 아닐까요? 객체의 추상화는 클래스가 더 가까워 보입니다.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>객체 생성 → 의존 설정 → 초기화 → 사용 → 소멸 과정의 생명주기를 가지고 있습니다. Bean은 스프링 컨테이너에 의해 생명주기를 관리하며 빈 초기화방법은 @PostConstruct 를 빈 소멸에서는 @PreDestroy 를 사용합니다.</p>
`@PostConstruct` 가 빈 초기화 방법인가요? 확인 부탁드려요 ㅎㅎ

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>DI는 세가지 방법이 있습니다. 생성자 삽입, Setter를 이용한 메소드 매개 변수 삽입, 필드 주입이 있습니다.</p>
보통 Injection은 주입으로 많이들 번역하는 것 같아요~

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>DI는 세가지 방법이 있습니다. 생성자 삽입, Setter를 이용한 메소드 매개 변수 삽입, 필드 주입이 있습니다.</p>
아래의 내용과도 좀 달라지네요~

2021-02-07 15:41 UTC, ksundong commented on README.md
> +    <li>가급적 읽기 전용으로 만들고, 필드 대신에 자바에서 공유되지 않는 지역변수, 파라미터, ThreadLocal 등을 사용합니다.</li>
사실 제가 의도했던거는 싱글턴 패턴을 멀티스레드 환경에서 구현하기 위해 사용하는 기법이었는데
그 부분도 학습해보시면 도움이 되실거에요
힌트는 더블 체킹 라킹(Double Checking Locking)입니다.

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>푸시가 될 때마다 코드를 병합하고, 테스트 코드와 빌드를 수행하면서 자동으로 코드가 통합되어 더는 수동으로 코드를 통합할 필요가 없어져 개발에만 신경을 쓸 수 있습니다.</p>
푸시가 될 때마다 일수도 있고, 이는 설정하기 나름인 것 같습니다!
요지는, 지속적으로 테스트 코드, 빌드를 수행하면서 코드가 크래시 되지 않고 배포가능한 상태를 만들기 위함이죠!

2021-02-07 15:41 UTC, ksundong commented on README.md
> +  <p>이 CI / CD의 중요한 것은 테스트 자동화입니다. 프로젝트의 완전한 상태임을 보장하기 위해 테스트 코드가 구현되어 있어야 합니다.</p>
중요한 것 보다는 중요한 부분은이 더 적절해보입니다.