안녕하세요 레포를 보던중 html태그 내에서 마크다운 문법을 쓰지 않고 작성을 하셔서 도움 될까 보내봅니다.
ksundong/backend-interview-question pull request #18
Opened 2021-02-26 16:04 UTC by hiro032

작성하신것을 봤는데 토글 기능때문에 마크다운을 포기하고  html로 쓰신거같아서 보내봅니다.
대부분 글에 <summary> 태그 밑에 <br>을 추가 하셨던데 이 <br>태그를 추가하지 않고, 바로 < p>태그 후에 토글 내용을 작성하시면, 내부에서 마크다운 문법을 적용할 수 있습니다.

예시)
<details><summary style="color:skyblue">CLICK ME</summary>
<p>

#### yes, even hidden code blocks!
## hi

```python
print("hello world!")
```

</p>
</details>

혹시 알았던 사실이라면 죄송합니다.

2021-02-26 16:11 UTC, hiro032 commented
> 작성하신것을 봤는데 토글 기능때문에 마크다운을 포기하고 html로 쓰신거같아서 보내봅니다.
> 대부분 글에 summary 태그 밑에 br을 추가 하셨던데 이 br태그를 추가하지 않고, 바로 < p>태그 후에 토글 내용을 작성하시면, 내부에서 마크다운 문법을 적용할 수 있습니다.
> 
> 예시)
> 
> CLICK ME
> 혹시 이미 알았지만 안쓰시던 거라면 죄송합니다.

예시)
<details><summary style="color:skyblue">CLICK ME</summary>
<p>

#### yes, even hidden code blocks!
## hi

```python
print("hello world!")
```

</p>
</details>

2021-02-26 16:11 UTC, hiro032 commented
`예시)
<details><summary style="color:skyblue">CLICK ME</summary>
<p>

#### yes, even hidden code blocks!
## hi

```python
print("hello world!")
```

</p>
</details>`

2021-02-27 13:24 UTC, ksundong requested changes
안녕하세요! 제안 감사드립니다!
<br> 때문에 발생한 문제였군요. 요즘 바빠서 여기에 신경을 못쓰고 있었는데 나중에 차차 수정해봐야겠어요.
약간 lint가 되지 않은 부분 때문에 변경요청 드립니다. 즐거운 연휴되세요~

2021-02-27 13:24 UTC, ksundong commented on README.md
> +## html내 마크다운 문법 사용법 _ hiro
앗 혹시 실례가 안된다면 닉네임 부분은 빼주실 수 있을까요?

2021-02-27 13:24 UTC, ksundong commented on README.md
> +예시)
요소 사이에 빈 라인을 추가해주세요!

2021-02-27 13:27 UTC, hiro032 commented on README.md
> +예시)
@ksundong 음 어떤식으로 하는게 좋을까요?? 위치도 적절한지 모르겠어서... 그냥 수정할 생각으로 보내봤던거라. 
위치나, 어떤식으로 변경하는게 좋을지 써주시면 수정하겠습니다.

2021-02-27 13:32 UTC, hiro032 commented on README.md
> +예시)
우선은 이렇게 수정을 해봤습니다. 위치가 적절한지는 잘 모르겠는데...
추가적인 수정이 필요하면 말씀해주세요!

2021-02-28 14:35 UTC, ksundong approved these changes
안녕하세요! markdown 문서 lint rule에 따라서 한 줄 개행을 추가한 부분을 제안드립니다.
기여해주셔서 감사합니다~

2021-02-28 14:35 UTC, ksundong commented on README.md
> +html태그 밑에 빈 라인을 추가해야 마크다운이 적용된다.
```suggestion
## html내 마크다운 문법 사용법

html태그 밑에 빈 라인을 추가해야 마크다운이 적용된다.
```

2021-02-28 14:35 UTC, ksundong commented on README.md
> +<details><summary style="color:skyblue">CLICK ME</summary>
```suggestion
예시)

<details><summary style="color:skyblue">CLICK ME</summary>
```

2021-02-28 14:35 UTC, ksundong commented on README.md
> +```
```suggestion
#### yes, even hidden code blocks!

## hi

**강조**

- 1
- 2
- 3

```python
print("hello world!")
```
```

2021-03-07 02:27 UTC, merged