[UPDATE] README.md
ksundong/backend-interview-question pull request #20
Opened 2021-04-09 17:22 UTC by jjmin321

2021-04-10 14:44 UTC, ksundong requested changes
기여 감사합니다! 몇 가지 변경해주셨으면 하는 부분과 생각해봤으면 하는 부분이 있어서 리뷰 남깁니다!

2021-04-10 14:44 UTC, ksundong commented on README.md
> +  <p>@Component : 개발자가 작성한 class를 Bean으로 만들기 위해 사용합니다.</p>
이 부분은 좀 더 고민을 해보는게 좋을 것 같습니다.
저는 https://stackoverflow.com/questions/10604298/spring-component-versus-bean
이런 내용을 생각했는데
한국어로 검색해보니 작성하신 내용이 많이 나오네요!
저도 공부가 많이 됐습니다 감사합니다!

2021-04-11 08:21 UTC, jjmin321 reviewed
오타 수정하였으며 추상적인 개념들 보충하여 올렸습니다

2021-04-11 12:42 UTC, ksundong approved these changes
LGTM! 💯

2021-04-11 12:43 UTC, merged