Dispatcher Servlet 동작 원리 추가
ksundong/backend-interview-question pull request #21
Opened 2021-04-21 11:02 UTC by ydh6226

2021-05-12 13:04 UTC, ksundong requested changes
안녕하세요! 리뷰가 늦어져서 죄송합니다 ㅠㅠ
저도 조금 학습을 다시 하고 리뷰를 했는데요, 확인해주시면 감사하겠습니다!
기여 감사합니다!

2021-05-12 13:04 UTC, ksundong commented on README.md
> +  <p>7. 반환된 뷰를 통해 뷰를 렌더링한다.</p>
최근에는 RestController도 자주 사용하기 때문에 좀더 일반적인 내용으로 변경해주시는게 좋을 것 같아요.
ReturnValueHandler에 위임을 하는 형태로 구현된다고 알고있는데, 더 자세히 설명하려면 더 확인을 해봐야겠네요.
`@ResponseBody` 를 사용한 경우 ModelAndView는 null이 되는 것으로 알고있습니다.

2023-12-20 14:47 UTC, Joyykim commented on README.md
> +  <p>7. 반환된 뷰를 통해 뷰를 렌더링한다.</p>
```suggestion
  <p>5. 핸들러 어댑터는 핸들러가 반환하는 정보를 ModelAndView로 변환해서 반환한다.</p>
  <p>6. 뷰 리졸버를 호출한다.</p>
  <p>7. 뷰 리졸버가 뷰의 논리 이름을 물리 이름으로 바꾸고 렌더링 역할을 담당하는 뷰 객체를 반환한다.</p>
  <p>8. 반환된 뷰를 통해 뷰를 렌더링한다.</p>
```

2026-01-27 12:51 UTC, ksundong commented
더이상 활동이 없어 close 합니다.

2026-01-27 12:51 UTC, closed without merging