update : 네트워크 파트 웹서버 질문 업데이트
ksundong/backend-interview-question pull request #44
Opened 2023-06-30 10:25 UTC by swj9707

빠진 부분이 있는 것 같아서 혹시나 싶어서 PR 올립니다. 
제 답변이 맞을 지 모르겠습니다...ㅠ 괜찮으시다면 반영 해 주시면 감사하겠습니다.

2023-06-30 13:24 UTC, ksundong requested changes
기여해주셔서 감사합니다!
몇가지 제안을 드리니 찬찬히 검토하시고 다시 리뷰요청 주시면 감사하겠습니다~

2023-06-30 13:24 UTC, ksundong commented on README.md
> +  <p>그러므로 Apache와 Nginx는 애플리케이션 레이어에서 동작합니다.</p>
단락(paragraph) 태그는 단락 구분이 필요할 때 사용해주세요.
좀 더 매끄럽게 한 문장으로 되면 좋을 것 같습니다~
```suggestion
  <p>
  Apache와 Nginx는 HTTP 프로토콜을 통해 데이터를 클라이언트에게 제공 해 주는 웹서버 역할을 합니다. HTTP 프로토콜은 OSI 7 계층 중 7번째 계층인 애플리케이션 레이어에서 브라우저와 서버 간 데이터 통신을 위한 프로토콜입니다. 그러므로 Apache와 Nginx는 애플리케이션 레이어에서 동작합니다.
  </p>
```

2023-06-30 13:24 UTC, ksundong commented on README.md
> +  <p>그러므로 Apache와 Nginx는 애플리케이션 레이어에서 동작합니다.</p>
e.g.)
Apache와 NGINX는 HTTP 웹 서버로, 이들이 동작하는 HTTP 프로토콜은 OSI 7 Layer 중 7계층인 애플리케이션 Layer 에 해당하는 프로토콜입니다. 따라서 Apache와 NGINX는 7계층인 애플리케이션 레이어에서 동작합니다.

정도로 표현하면 어떨까요?

좀 더 나아가서 TCP/IP 4계층에서는 4계층에서 동작하며, TCP/IP 를 통해 동작함도 설명해주면 좋을 것 같네요!

2023-06-30 13:24 UTC, ksundong commented on README.md
> +  <p>만약 API 서버 등 애플리케이션에 해당 경로를 설정하였다면, 80 혹은 443 포트로 전달 된 요청을 웹 서버가 받아서 WAS에 대신 전달합니다. 이를 리버스프록시라고 합니다.</p>
여기도 마찬가지로 잘 작성해주셨는데, 단락 태그를 조금 고쳐서 사용하면 좋겠습니다!

2023-06-30 13:24 UTC, ksundong commented on README.md
> +  <p>만약 API 서버 등 애플리케이션에 해당 경로를 설정하였다면, 80 혹은 443 포트로 전달 된 요청을 웹 서버가 받아서 WAS에 대신 전달합니다. 이를 리버스프록시라고 합니다.</p>
또 일반적인 라우팅의 경우는 말씀하신대로 layer7 에서 동작하겠지만
Apache는 제가 사용을 안해봐서 잘 모르고 😅
NGINX의 경우에는 Layer4의 load balancer로 사용하는 사례도 있습니다.

2023-07-01 05:34 UTC, swj9707 commented on README.md
> +  <p>그러므로 Apache와 Nginx는 애플리케이션 레이어에서 동작합니다.</p>
넵 말씀하신 내용 추가해서 수정 다시 진행하겠습니다.

2023-07-01 05:50 UTC, swj9707 commented on README.md
> +  <p>만약 API 서버 등 애플리케이션에 해당 경로를 설정하였다면, 80 혹은 443 포트로 전달 된 요청을 웹 서버가 받아서 WAS에 대신 전달합니다. 이를 리버스프록시라고 합니다.</p>
넵 아파치는 자체적으로 L4 로드밸런싱 기능이 없는것으로 알고있고...NGINX는 말씀하신대로 upstream 블록으로 묶어서 사용하죠. 내용 보완했습니다.

2023-07-01 09:53 UTC, ksundong approved these changes
LGTM!

2023-07-01 09:54 UTC, merged