Java,Javascript,커뮤니케이션등 문제 추가.
ksundong/backend-interview-question pull request #46
Opened 2023-08-02 05:02 UTC by Chung10Kr

이렇게 좋은 레파지토리를 우연히 발견하여
처음 기여합니다.

제가 그동안 인터뷰시 받았던 질문들 추가 합니다.

2023-08-06 15:26 UTC, ksundong requested changes
기여 감사합니다!
몇가지 변경 포인트들이 보여서 변경요청드립니다.
즐거운 한 주 되세요!

2023-08-06 15:26 UTC, ksundong commented on README.md
> +  인덱스를 생성전에 충분한 분석 및 검토가 필요하여 시스템을 균형있게 유지해야 한다.
여기도 `paragraph` 태그로 묶어주시면 감사하겠습니다 🙇‍♂️

2023-08-06 15:26 UTC, ksundong commented on README.md
> +  </details>
요건 우선순위가 낮은 질문인 것 같아 위치를 아래로 조정해주시면 좋을 것 같습니다.
최근의 면접에선 해당 질문을 들어본 적은 없었긴하네요~

2023-08-06 15:26 UTC, ksundong commented on README.md
> +</details>
가능하다면 질문의 우선순위를 고려해서 하단에 추가해주시면 좋을 것 같습니다!
기여 감사합니다!

2023-08-06 15:26 UTC, ksundong commented on README.md
> +</details>
여기는 devops 보다는, 기타에 가까운 질문이라고 생각됩니다.
그리고 이런 경우에는 답변보다는 질문만 남겨주시면 좋을 것 같습니다~ (스스로 생각해볼 수 있게끔요~)

2023-08-06 15:26 UTC, ksundong commented on README.md
> +</details>
```suggestion
<details>
  <summary>고객과의 갈등이 있을 경우, 이를 어떻게 해결할 것인가요?</summary>
  </br>
  <p></p>
</details>
```

개인적으로는 이런 질문은 신입에게 적절하지 않은 질문 같기는 합니다.

2023-08-06 15:26 UTC, ksundong commented on README.md
> +</details>
해당 질문도 신입에게는 크게 면접 준비에 메리트 있는 질문은 아닌 것으로 보이네요~
```suggestion
```

2023-08-06 15:26 UTC, ksundong commented on README.md
> +  <summary>코딩테스트의 해당 언어를 선택한 이유?</summary>
```suggestion
  <summary>코딩테스트에서 해당 언어를 선택하신 이유는 무엇인가요?</summary>
```

2023-08-06 15:26 UTC, ksundong commented on README.md
> +  을 물어보더라구요..회사에서 이 지원자의 기술 선호도, 프로그래밍 지식의 폭, 언어에 대한 이해, 업무 적합성 등을 알고 싶어서 물어 본거 아닐까 합니다.
```suggestion
  <p>Java(Spring), Javascript(Node), 파이썬등 여러가지 언어가 있었는데 왜 해당 언어로 코딩 테스트를 했는지</p>
  <p>해당 언어가 익숙해서 인지, 코딩 테스트 풀기 편해서인지, 우리 회사가 사용하는 언어여서 인지</p>
  <p>(*질문 작성자 주)을 물어보더라구요..회사에서 이 지원자의 기술 선호도, 프로그래밍 지식의 폭, 언어에 대한 이해, 업무 적합성 등을 알고 싶어서 물어 본거 아닐까 합니다.</p>
```

2023-08-06 15:26 UTC, ksundong commented on README.md
> +  을 물어보더라구요..회사에서 이 지원자의 기술 선호도, 프로그래밍 지식의 폭, 언어에 대한 이해, 업무 적합성 등을 알고 싶어서 물어 본거 아닐까 합니다.
개인적으로는 쓸모 없는 질문이라고는 생각하지만, 그래도 충분히 나올 수 있는 질문으로 보이네요!

2023-08-06 16:41 UTC, Chung10Kr commented on README.md
> +  을 물어보더라구요..회사에서 이 지원자의 기술 선호도, 프로그래밍 지식의 폭, 언어에 대한 이해, 업무 적합성 등을 알고 싶어서 물어 본거 아닐까 합니다.
경력으로 면접을 몇번 봤는데 한 2번정도 질문 받았었어요
특정 언어만 사용하는 회사가 아닌 여러가지 언어를 사용하는 회사 면접볼 때 물어보시더라구요

2023-08-13 14:07 UTC, ksundong commented on README.md
> +  을 물어보더라구요..회사에서 이 지원자의 기술 선호도, 프로그래밍 지식의 폭, 언어에 대한 이해, 업무 적합성 등을 알고 싶어서 물어 본거 아닐까 합니다.
넵넵 감사합니다!

2023-08-13 14:07 UTC, ksundong approved these changes
수정내용 확인되어 Approve 합니다.
기여감사합니다. 🙇‍♂️

2023-08-13 14:07 UTC, merged